spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
#        - id: products-command-service
#          uri: http://localhost:8070
#          predicates:
#            - Path=/products/command/**
#        - id: products-query-service
#          uri: http://localhost:8071
#          predicates:
#            - Path=/products/query/**

         - id: user-registration-route
           uri: http://localhost:7001
           predicates:
             - Path=/api/v1/user/registration

         - id: user-service
           uri: http://localhost:7001
           predicates:
             - Path=/api/v1/user/**
           filters:
             - name: TestGateWayFilterFactory


         - id: restaurant-and-item-public-route
           uri: http://localhost:8073
           predicates:
             - Path=/api/v1/restaurant/**, /api/v1/item/**
#             - Path=/api/v1/item/**

         - id: restaurant-and-item-admin-route
           uri: http://localhost:8073
           predicates:
             - Path=/api/v1/admin/restaurant/**, /api/v1/admin/item/**
#             - Path=/api/v1/admin/item/**
           filters:
             - name: TestGateWayFilterFactory


         - id: inventory-service
           uri: http://localhost:8074
           predicates:
             - Path=/api/v1/stock/**
           filters:
             - name: TestGateWayFilterFactory

         - id: cart-service
           uri: http://localhost:8075
           predicates:
             - Path=/api/v1/cart/**
           filters:
             - name: TestGateWayFilterFactory

         - id: order-service
           uri: http://localhost:8076
           predicates:
             - Path=/api/v1/order/**
           filters:
             - name: TestGateWayFilterFactory



  security:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/restaurant
            jwk-set-uri: http://localhost:8080/realms/restaurant/protocol/openid-connect/certs


server.port: 8001

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE