spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
#        - id: products-command-service
#          uri: http://localhost:8070
#          predicates:
#            - Path=/products/command/**
#        - id: products-query-service
#          uri: http://localhost:8071
#          predicates:
#            - Path=/products/query/**
         - id: test-redirection
           uri: http://localhost:10001
#           predicates:
#             - Path=/test/**
           predicates:
             - Path=/**
#           filters:
#             - name: CustomAuthFilter
           filters:
             - name: TestGateWayFilterFactory
#               args:
#                 customValue: "Meow435"
#                 q: "w"

  security:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/restaurant
            jwk-set-uri: http://localhost:8080/realms/restaurant/protocol/openid-connect/certs


server.port: 8001

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE