services:
  redis:
    image: redis:latest
    container_name: redis_cache
    environment:
      REDIS_PASSWORD: default
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data/:/data
